import {React,useState,render,Notice,Button,Input,Textarea,Field,FieldLabel,FieldDescription,FieldError,FieldGroup,FieldSet,FieldLegend,InputGroup,InputGroupInput,InputGroupAddon,InputGroupText} from './shared';
function Page({scene}){
 const [step,setStep]=useState(1),[draft,setDraft]=useState(scene.data.form),[error,setError]=useState(''),[failed,setFailed]=useState(false),[done,setDone]=useState(false);
 function next(){if(!draft.name.trim()){setError('请输入资料名称');document.getElementById('name').focus();return;}setError('');setStep(2);}
 function save(){if(!draft.owner.trim()){setError('请输入负责人');document.getElementById('owner').focus();return;}if(scene.id==='failure'&&!failed){setFailed(true);setError('提交失败，所有步骤输入已保留，请重试。');return;}setError('');setDone(true);}
 const readonly=scene.id==='no-permission',nameError=error==='请输入资料名称',ownerError=error==='请输入负责人';
 return <div className="form-layout"><aside className="step-aside" aria-label="填写进度"><ol className="step-list"><li aria-current={step===1?'step':undefined} className={step===1?'current':'completed'}><span className="step-number">{step===1?'1':'✓'}</span><div><strong>资料信息</strong><p>名称与补充说明</p></div></li><li aria-current={step===2?'step':undefined} className={step===2?'current':''}><span className="step-number">2</span><div><strong>负责人及确认</strong><p>核对内容后提交</p></div></li></ol><div className="step-help"><strong>安心填写</strong><p>步骤之间可返回修改。提交失败后，已填内容会保留。</p><p>关闭或重置页面会清除本地输入。</p></div></aside><section className="surface form-surface"><h2>步骤 {step}/2：{step===1?'资料信息':'负责人及确认'}</h2>{readonly&&<Notice>当前资料仅可查看，不能提交修改。</Notice>}<div className="form-body"><FieldSet disabled={readonly||done}><FieldLegend>{step===1?'基本信息':'责任与确认'}</FieldLegend><FieldGroup>{step===1?<><Field data-invalid={nameError}><FieldLabel htmlFor="name">资料名称</FieldLabel><InputGroup><InputGroupInput id="name" value={draft.name} aria-invalid={nameError} aria-describedby={nameError?'name-help name-error':'name-help'} onChange={e=>{setDraft({...draft,name:e.target.value});if(nameError)setError('');}}/><InputGroupAddon align="inline-end"><InputGroupText>必填</InputGroupText></InputGroupAddon></InputGroup><FieldDescription id="name-help">用于查询和确认；返回本步骤会保留输入。</FieldDescription>{nameError&&<FieldError id="name-error">{error}</FieldError>}</Field><Field><FieldLabel htmlFor="note">说明</FieldLabel><Textarea id="note" value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></Field></>:<><p>资料：{draft.name}</p><p>说明：{draft.note||'未填写'}</p><Field data-invalid={ownerError}><FieldLabel htmlFor="owner">负责人</FieldLabel><Input id="owner" value={draft.owner} aria-invalid={ownerError} aria-describedby={ownerError?'owner-help owner-error':'owner-help'} onChange={e=>{setDraft({...draft,owner:e.target.value});if(ownerError)setError('');}}/><FieldDescription id="owner-help">确认资料的负责人；提交为本地模拟。</FieldDescription>{ownerError&&<FieldError id="owner-error">{error}</FieldError>}</Field></>}</FieldGroup></FieldSet>{error&&!nameError&&!ownerError&&<Notice error>{error}</Notice>}{done&&<Notice>提交成功（本地模拟）。</Notice>}</div><div className="toolbar form-actions material-surface"><span className="action-context">{done?'本次填写已完成':step===1?'下一步：负责人及确认':'请核对后提交'}</span>{step===2&&<Button variant="outline" disabled={done} onClick={()=>{setStep(1);setError('');}}>上一步</Button>}{step===1?<Button disabled={readonly||done} onClick={next}>下一步</Button>:<Button disabled={readonly||done} onClick={save}>{done?'已提交':failed?'重试提交':'确认提交'}</Button>}</div></section></div>;
}
render(Page,'分步表单');
