import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
const root=path.resolve(process.argv[2]||process.cwd()),out=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'yss-json-distribution-')));console.log('evidence: '+out);const results=[];
function run(cmd,args,cwd=root){const r=spawnSync(cmd,args,{cwd,encoding:'utf8',maxBuffer:8*1024*1024,timeout:180000});if(r.error)throw r.error;return r;}
for(const name of ['create-yss-spec','create-yss-strategic-design','create-yss-harness-backend','create-yss-harness-frontend']){
 const source=path.join(root,'submodules',name),meta=JSON.parse(fs.readFileSync(source+'/package.json'));const packed=run('npm',['pack','--ignore-scripts','--json','--pack-destination',out],source);assert.equal(packed.status,0,packed.stderr);fs.writeFileSync(out+'/'+name+'-pack.json',packed.stdout);const report=JSON.parse(packed.stdout);const filename=(Array.isArray(report)?report[0]:report.filename?report:report[meta.name])?.filename;assert.ok(filename,packed.stdout.slice(0,700));const tar=path.join(out,filename);
 const install=path.join(out,name+'-install');fs.mkdirSync(install,{recursive:true});const installed=run('npm',['install','--ignore-scripts','--no-audit','--no-fund','--prefix',install,tar]);assert.equal(installed.status,0,installed.stderr);
 const bin=typeof meta.bin==='string'?meta.bin:Object.values(meta.bin)[0],target=path.join(out,name+'-project-v4');
 const init=run(process.execPath,[path.join(install,'node_modules',meta.name,bin),'--project-name','JSON Asset Fixture','--business-domain','合成验证','--team-size','1','--target-dir',target,...(name==='create-yss-spec'?['--agent-runtime','codex']:[])]);fs.writeFileSync(out+'/'+name+'-init.log',init.stdout+init.stderr);assert.equal(init.status,0,init.stderr);
 for(const ref of ['scripts/lib/structured-assets.mjs','scripts/lib/asset-transactions.mjs','scripts/lib/asset-migration.mjs'])assert.equal(fs.readFileSync(target+'/'+ref,'utf8'),fs.readFileSync(root+'/'+ref,'utf8'),name+': '+ref);
 fs.mkdirSync(target+'/docs/probe',{recursive:true});const value=JSON.parse(fs.readFileSync(target+'/.template-spec/process/templates/lifecycle-checkpoint-template.json'));fs.writeFileSync(target+'/docs/probe/checkpoint.json',JSON.stringify(value));
 const args=[target+'/scripts/contract','validate','docs/probe/checkpoint.json','--kind','checkpoint','--structure-only','--root',target];const positive=run(process.execPath,args);assert.equal(positive.status,0,positive.stderr);value.status='invalid';fs.writeFileSync(target+'/docs/probe/checkpoint.json',JSON.stringify(value));const negative=run(process.execPath,args);assert.notEqual(negative.status,0);
 results.push({name,sourceState:'working-tree',pack:'ignore-scripts-local-test-only',install_exit:installed.status,init_exit:init.status,positive_exit:positive.status,negative_exit:negative.status,publication:'not-performed'});fs.writeFileSync(out+'/results.json',JSON.stringify(results,null,2)+'\n');console.log(name+' passed');
}
