import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import test from 'node:test';
import {makeSkillSourceLock} from '../../../scripts/lib/profile-skills-preparation.mjs';

for(const profile of ['backend','frontend'])test(profile+' independent clone prepares once from pinned local source and stays clean offline',t=>{
  const repo=fileURLToPath(new URL('../../../../',import.meta.url));
  const tmp=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'standalone-skills-'));
  t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
  const source=path.join(tmp,'spec'),original=path.join(tmp,profile),clone=path.join(tmp,'clone');
  const put=(root,ref,bytes)=>{const file=path.join(root,ref);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes);};
  const git=(root,...args)=>{const r=spawnSync('git',['-C',root,...args],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};
  const init=root=>{fs.mkdirSync(root,{recursive:true});git(root,'init','-q');git(root,'config','user.email','fixture@example.invalid');git(root,'config','user.name','fixture');git(root,'config','core.autocrlf','false');};
  init(source);
  put(source,'yss-project.yaml','schema_version: 1\nrepository_mode: template-source\n');
  put(source,'.template-source/distribution/bundle-profile.json','{"schemaVersion":1,"profile":"spec"}');
  for(const ref of ['scripts/lib/profile-skill-sync.mjs','.template-source/scripts/lib/profile-skills-preparation.mjs'])put(source,ref,fs.readFileSync(path.join(repo,ref)));
  put(source,'.agents/skills/shared/SKILL.md','shared source\n');
  const config={schema_version:1,profiles:{[profile]:{materialization:'generated',exact:[{id:'shared'}],local_only:['local']}}};
  put(source,'.template-source/profile-skill-sync.json',JSON.stringify(config));
  git(source,'add','.');git(source,'commit','-qm','fixed source fixture');
  init(original);
  put(original,'yss-project.yaml','schema_version: 1\nrepository_mode: template-source\n');
  put(original,'.template-spec/process/harness-profile.yaml','instantiation:\n  native_profile: '+profile+'\n');
  put(original,'.agents/skills/local/SKILL.md','local\n');
  put(original,'scripts/prepare-skills',fs.readFileSync(path.join(repo,'.template-source/scripts/prepare-profile-skills.mjs')));
  put(original,'scripts/vendor/yaml.mjs',fs.readFileSync(path.join(repo,'scripts/vendor/yaml.mjs')));
  put(original,'.template-source/profile-skills-source.json',JSON.stringify(makeSkillSourceLock({root:source,config,profile})));
  put(original,'.gitignore','/.agents/skills/shared/\n/.codex/skills/shared\n/.cursor/skills/shared\n/.pi/skills/shared\n/.template-source/profile-skills-prepared.json\n');
  git(original,'add','.');git(original,'commit','-qm','source-only profile fixture');
  const cloned=spawnSync('git',['clone','-q','--local',original,clone],{encoding:'utf8'});assert.equal(cloned.status,0,cloned.stderr);
  const run=(...args)=>spawnSync(process.execPath,['scripts/prepare-skills',...args],{cwd:clone,encoding:'utf8'});
  assert.equal(run('--check').status,1);
  let r=run('--source',source,'--apply');assert.equal(r.status,0,r.stderr);
  assert.equal(git(clone,'status','--porcelain'),'');
  assert.equal(run('--check').status,0);
  for(const rt of ['.agents','.codex','.cursor','.pi'])assert.equal(fs.readFileSync(path.join(clone,rt,'skills/shared/SKILL.md'),'utf8'),'shared source\n');
  r=run('--source',source,'--apply');assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).written,0);
  put(source,'.agents/skills/shared/SKILL.md','dirty source');r=run('--source',source,'--apply');assert.equal(r.status,1);assert.match(r.stderr,/未提交/);
  assert.equal(run('--check').status,0,'cached check must not depend on source checkout');
  put(clone,'.agents/skills/shared/SKILL.md','user edit');assert.equal(run('--check').status,1);
  put(source,'.agents/skills/shared/SKILL.md','shared source\n');r=run('--source',source,'--apply');assert.equal(r.status,1);assert.match(r.stderr,/冲突/);assert.equal(fs.readFileSync(path.join(clone,'.agents/skills/shared/SKILL.md'),'utf8'),'user edit');
  put(source,'new.txt','future');git(source,'add','.');git(source,'commit','-qm','future source');assert.match(run('--source',source,'--apply').stderr,/提交.*不一致/);
});
