import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {fileURLToPath,pathToFileURL} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),{chromium}=await import(process.env.YSS_PLAYWRIGHT_MODULE||'playwright');
const temp=await mkdtemp(path.join(os.tmpdir(),'yss-vue-zoom-')),extension=path.join(temp,'extension');await mkdir(extension);await writeFile(path.join(extension,'manifest.json'),JSON.stringify({manifest_version:3,name:'Local study zoom verification',version:'1.0',permissions:['tabs'],background:{service_worker:'worker.js'}}));await writeFile(path.join(extension,'worker.js'),'chrome.runtime.onInstalled.addListener(()=>{});');
const context=await chromium.launchPersistentContext(path.join(temp,'profile'),{headless:true,channel:'chromium',viewport:null,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`]});await context.setOffline(true);const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');const p=await context.newPage(),rows=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
async function contrasts(selectors){return p.evaluate(selectors=>{const cv=document.createElement('canvas');cv.width=cv.height=1;const ctx=cv.getContext('2d');function rgb(color,base){ctx.clearRect(0,0,1,1);ctx.fillStyle=base;ctx.fillRect(0,0,1,1);ctx.fillStyle=color;ctx.fillRect(0,0,1,1);return [...ctx.getImageData(0,0,1,1).data].slice(0,3);}function luminance(c){return c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);}return selectors.map(({label,text,surface,worst})=>{const c=getComputedStyle(document.querySelector(text)).color,b=getComputedStyle(document.querySelector(surface)).backgroundColor;const ratios=(worst?['black','white']:['white']).map(base=>{const bg=rgb(b,base),fg=rgb(c,`rgb(${bg.join(',')})`),l1=luminance(bg),l2=luminance(fg);return (Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05);});return{label,color:c,background:b,minRatio:Math.min(...ratios),checkedBackdrops:worst?'black and white':'opaque white'};});},selectors);}
try{
 for(const mode of ['standard','glass'])for(const page of ['list-detail','multi-step']){
  const url=pathToFileURL(path.join(here,'comparisons',page,'variants',mode,'index.html')).href+'#scenario='+(page==='multi-step'?'failure':'primary');await p.goto(url);await p.locator('h1').waitFor();
  const items=[{label:'bar secondary',text:'.environment',surface:'.workspace-bar',worst:mode==='glass'},{label:'heading',text:'h1',surface:'body'}];
  if(page==='multi-step'){await p.getByRole('button',{name:'下一步',exact:true}).click();items.push({label:'field error',text:'[data-slot="field-error"]',surface:'.form-surface'},{label:'primary button',text:'.form-actions [data-slot="button"]',surface:'.form-actions [data-slot="button"]'},{label:'action hint',text:'.action-context',surface:'.form-actions',worst:mode==='glass'});}else{await p.getByRole('button',{name:'更多 M-001',exact:true}).click();items.push({label:'menu item',text:'[data-slot="dropdown-menu-item"]',surface:'[data-slot="dropdown-menu-content"]',worst:mode==='glass'});}
  const contrast=await contrasts(items);for(const item of contrast)assert(item.minRatio>=4.5,JSON.stringify(item));
  await p.setViewportSize({width:1440,height:900});await p.screenshot({path:path.join(here,'screenshots',`${page}-${mode}-interaction.png`),fullPage:true});await p.keyboard.press('Escape');
  const zoom=await worker.evaluate(async url=>{const tab=(await chrome.tabs.query({})).find(t=>t.url===url);await chrome.tabs.setZoom(tab.id,2);return await chrome.tabs.getZoom(tab.id);},url);assert.equal(zoom,2);await p.waitForFunction(()=>devicePixelRatio>=2);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  if(page==='multi-step'){await p.locator('#name').fill('200% 缩放资料');await p.getByRole('button',{name:'下一步',exact:true}).click();await p.locator('#owner').fill('缩放检查');await p.getByRole('button',{name:'确认提交',exact:true}).click();await p.getByRole('button',{name:'重试提交',exact:true}).click();await p.getByText('提交成功（本地模拟）。',{exact:true}).waitFor();}else{await p.getByRole('button',{name:'查看 M-001',exact:true}).click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');}
  await p.screenshot({path:path.join(here,'screenshots',`${page}-${mode}-200.png`),fullPage:true});rows.push({page,mode,zoom,geometry:await p.evaluate(()=>({width:innerWidth,dpr:devicePixelRatio})),contrast,status:'passed'});
  await worker.evaluate(async url=>{const tab=(await chrome.tabs.query({})).find(t=>t.url===url);await chrome.tabs.setZoom(tab.id,1);},url);
 }
 assert.deepEqual(errors,[]);await writeFile(path.join(here,'evidence/visual-checks.json'),JSON.stringify({status:'passed',zoomMechanism:'chrome.tabs.setZoom/getZoom in isolated profile',rows,errors},null,2));console.log(JSON.stringify({status:'passed',rows:rows.length}));
}catch(error){await writeFile(path.join(here,'evidence/visual-failure.json'),JSON.stringify({error:error.stack,rows,errors},null,2));throw error;}finally{await context.close();}
