import {React,useState,render,Notice,Button,Input,Label,Badge,Checkbox,Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from './shared';
function Page({scene}){
 const origin=React.useRef(null);
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('asc'),[page,setPage]=useState(0),[selected,setSelected]=useState([]),[detail,setDetail]=useState(null);
 const rows=scene.data.rows.filter(r=>(r.name+r.id).includes(query)&&(status==='all'||r.status===status)).sort((a,b)=>sort==='asc'?a.id.localeCompare(b.id):b.id.localeCompare(a.id));
 const size=2,visible=rows.slice(page*size,(page+1)*size),readonly=scene.id==='no-permission';
 function toggle(id){setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);}
 return <><section className="surface"><h2>查询条件</h2><div className="filters query-filters"><div><Label htmlFor="keyword">名称或编号</Label><Input id="keyword" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div><div><Label htmlFor="status">资料状态</Label><select id="status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">全部</option><option>待核对</option><option>已更新</option></select></div><Button variant="outline" onClick={()=>{setQuery('');setStatus('all');setPage(0);}}>重置筛选</Button></div></section>
 <section className="surface"><div className="toolbar"><h2>资料列表 · 共 {rows.length} 条</h2><Button variant="outline" onClick={()=>{setSort(sort==='asc'?'desc':'asc');setPage(0);}}>编号{sort==='asc'?'降序':'升序'}</Button><span role="status">已选择 {selected.length} 项</span></div><Notice>{readonly?'当前只读：选择操作不可用。':''}</Notice>
 <Table className="responsive-list"><TableHeader><TableRow>{['选择','编号','资料名称','状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.id} data-state={selected.includes(r.id)?'selected':undefined}><TableCell><Checkbox aria-label={`选择 ${r.id}`} disabled={readonly} checked={selected.includes(r.id)} onCheckedChange={()=>toggle(r.id)}/></TableCell><TableCell data-label="编号">{r.id}</TableCell><TableCell data-label="资料名称">{r.name}</TableCell><TableCell data-label="状态"><Badge variant="secondary">{r.status}</Badge></TableCell><TableCell><Button variant="outline" onClick={e=>{origin.current=e.currentTarget;setDetail(r);}} aria-label={`查看 ${r.id}`}>查看详情</Button></TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&<Notice>{scene.id==='loading'?'正在加载（固定评审状态）':'暂无符合条件的资料'}</Notice>}
 <div className="toolbar"><Button variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>上一页</Button><span>第 {page+1} 页</span><Button variant="outline" disabled={(page+1)*size>=rows.length} onClick={()=>setPage(page+1)}>下一页</Button></div></section>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent onCloseAutoFocus={e=>{e.preventDefault();origin.current?.focus();}}><DialogHeader><DialogTitle>资料详情</DialogTitle><DialogDescription>核对选中资料。</DialogDescription></DialogHeader>{detail&&<dl>{Object.entries(detail).map(([key,value])=><React.Fragment key={key}><dt>{({id:'编号',name:'资料名称',owner:'负责人',status:'状态',version:'版本'})[key]||key}</dt><dd>{String(value)}</dd></React.Fragment>)}</dl>}</DialogContent></Dialog></>;
}
render(Page,'查询与详情');
