import assert from 'node:assert/strict';
import {browserHarness,entry,layout,reset} from './browser-harness.mjs';
await browserHarness('workspace',async({page,width,check,capture})=>{
 const go=async(scene='primary',id='')=>{await page.goto('about:blank');await page.goto(entry('workspace',scene,id));};
 async function nav(title,module='资料管理'){
  if(width<768){await page.getByRole('button',{name:'切换模块',exact:true}).click();await page.getByRole('menuitem',{name:module,exact:true}).click();await page.getByRole('button',{name:'打开导航',exact:true}).click();await page.getByRole('navigation',{name:'窄屏页面导航',exact:true}).getByRole('button',{name:title,exact:true}).click();}
  else{await page.getByRole('navigation',{name:'模块导航',exact:true}).getByRole('button',{name:module,exact:true}).click();await page.locator('aside[aria-label="页面导航"]').getByRole('button',{name:title,exact:true}).click();}
  await page.getByRole('heading',{level:1,name:title,exact:true}).waitFor();
 }
 const tag=id=>page.locator(`[data-workspace-page="${id}"]`);
 await check('W01-W02-T01-T02-T04-draft-close-reopen',async()=>{
  await go();await nav('分步表单');await page.locator('#name').fill('跨页草稿');await page.locator('#note').fill('保留说明');await page.getByRole('button',{name:'下一步',exact:true}).click();await page.locator('#owner').fill('张明');await nav('查询与详情');await nav('分步表单');assert.equal(await tag('multi-step').count(),1);assert.equal(await page.locator('#owner').inputValue(),'张明');
  await page.getByRole('button',{name:'关闭 分步表单',exact:true}).click();await page.getByRole('button',{name:'保留页面',exact:true}).click();assert.equal(await page.locator('#owner').inputValue(),'张明');await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='关闭 分步表单');
  await page.getByRole('button',{name:'关闭 分步表单',exact:true}).click();await page.getByRole('button',{name:'放弃修改并关闭',exact:true}).click();assert.equal(await tag('multi-step').count(),0);await nav('分步表单');assert.equal(await page.locator('#name').inputValue(),'');
  if(width>=768){const toggle=page.getByRole('button',{name:width>=1200?'收起导航':'展开导航',exact:true});await toggle.click();await page.locator('aside[aria-label="页面导航"]').getByRole('button',{name:'组合查询',exact:true}).focus();if(width>=1200){await page.locator('[data-slot=tooltip-content]').filter({hasText:'组合查询'}).waitFor();await capture('collapsed-tooltip');}await nav('组合查询');assert.equal(await page.locator('[data-slot=tooltip-content]').count(),0);}
 });
 await check('W03-T03-T06-tag-keyboard-neighbor-overflow',async()=>{
  await go();await nav('分步表单');await nav('审批与权限','工作事项');await nav('高密度分析','分析中心');
  if(width>=768){await tag('multi-step').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>document.activeElement.dataset.workspacePage),'approval');assert.equal(await tag('analysis').getAttribute('aria-current'),'page');await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>document.activeElement.dataset.workspacePage),'list-detail');await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.dataset.workspacePage),'analysis');
  await page.keyboard.press('ArrowLeft');await page.keyboard.press('Enter');}else{await page.getByRole('button',{name:'已打开页面菜单',exact:true}).click();await page.getByRole('menuitem',{name:'审批与权限',exact:true}).click();await tag('approval').focus();}await page.getByRole('heading',{level:1,name:'审批与权限',exact:true}).waitFor();await page.keyboard.press('Delete');assert.equal(await tag('approval').count(),0);assert.equal(await tag('multi-step').getAttribute('aria-current'),'page');
  if(width<768){await page.getByRole('button',{name:'已打开页面菜单',exact:true}).click();await page.getByRole('menuitem',{name:'查询与详情',exact:true}).click();}await tag('list-detail').focus();await page.keyboard.press('Delete');assert.equal(await tag('list-detail').count(),1);await page.getByRole('button',{name:'已打开页面菜单',exact:true}).click();await page.getByRole('menuitem',{name:'高密度分析',exact:true}).click();await page.getByRole('heading',{level:1,name:'高密度分析',exact:true}).waitFor();await layout(page);await capture('tags');
 });
 await check('W04-W05-W06-list-retention-detail-focus',async()=>{
  await go();await page.getByRole('button',{name:'下一页',exact:true}).click();await page.getByRole('checkbox',{name:'选择 M-003',exact:true}).click();await page.getByRole('button',{name:'查看 M-003',exact:true}).click();
  if(width>=1200){assert.equal(await page.locator('.inline-detail').evaluate(e=>e.getBoundingClientRect().width),384);await page.getByRole('button',{name:'关闭详情',exact:true}).click();}else{await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');}
  await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='查看 M-003');await nav('分步表单');await nav('查询与详情');assert(await page.getByRole('checkbox',{name:'选择 M-003',exact:true}).isChecked());await page.getByText('第 2 页 / 共 2 页',{exact:true}).waitFor();
  await page.locator('#keyword').fill('归档');await nav('分步表单');await nav('查询与详情');assert.equal(await page.locator('#keyword').inputValue(),'归档');assert.equal(await page.locator('[data-slot="sheet-content"]').count(),0);await layout(page);await capture('query-detail');
 });
 await check('W07-form-error-retry',async()=>{
  await go('exceptions','multi-step');await page.getByRole('button',{name:'下一步',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'name');await page.locator('#name').fill('异常任务');await page.locator('#note').fill('返回保留');await page.getByRole('button',{name:'下一步',exact:true}).click();await page.locator('#owner').fill('张明');await page.getByRole('button',{name:'上一步',exact:true}).click();assert.equal(await page.locator('#note').inputValue(),'返回保留');await page.getByRole('button',{name:'下一步',exact:true}).click();await page.getByRole('button',{name:'确认提交',exact:true}).click();await page.getByRole('alert').waitFor();await page.getByRole('button',{name:'重试提交',exact:true}).click();await page.getByText('提交成功（本地模拟）。',{exact:true}).waitFor();
 });
 await check('W08-W09-approval-conflict-recovery',async()=>{
  await go('exceptions','approval');assert(await page.getByRole('button',{name:'通过 M-002',exact:true}).isDisabled());for(const id of ['M-001','M-003'])await page.getByRole('checkbox',{name:`选择 ${id}`,exact:true}).click();await page.getByRole('button',{name:'批量通过',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByRole('button',{name:'通过 M-001',exact:true}).count(),0);await page.getByRole('button',{name:'批量通过',exact:true}).click();assert.equal(await page.getByRole('button',{name:'通过 M-003',exact:true}).count(),0);
  await nav('冲突与恢复','工作事项');await page.getByRole('button',{name:'编辑 M-001',exact:true}).click();await page.locator('#name').fill('恢复草稿');await page.locator('#save').click();await page.locator('#reload').click();await page.getByRole('button',{name:'保留草稿',exact:true}).click();await page.keyboard.press('Escape');await nav('查询与详情');await nav('冲突与恢复','工作事项');await page.getByRole('button',{name:'继续编辑草稿',exact:true}).click();assert.equal(await page.locator('#name').inputValue(),'恢复草稿');await page.locator('#reload').click();await page.getByRole('button',{name:'放弃并重新加载',exact:true}).click();assert.equal(await page.locator('#version').textContent(),'2');await page.locator('#save').click();await page.getByText('保存成功（本地模拟）。',{exact:true}).waitFor();
 });
 await check('W10-T05-analysis-tabs',async()=>{
  await go('primary','analysis');await page.locator('#keyword').fill('张明');assert.equal(await page.locator('.metric-value').first().textContent(),'8');await page.getByRole('button',{name:'定位 M-001',exact:true}).click();await page.getByRole('region',{name:'定位资料',exact:true}).waitFor();await page.getByRole('tab',{name:'概览',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.getByRole('tabpanel').filter({hasText:'表格可横向滚动'}).waitFor();assert.equal(await page.locator('tbody tr').count(),8);if(width<768){await page.locator('.dense-region').focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.dense-region').scrollLeft>0);}await layout(page);await capture('analysis');
 });
 await check('W11-new-controls-cache-overlay-reset',async()=>{
  await go('primary','owner-validity');await page.locator('#validity-name').fill('负责人草稿');await page.locator('#form-owner').fill('U-002');await page.getByRole('option',{name:'张明 · U-002',exact:true}).click();await nav('组合查询');await page.locator('#query-owner').fill('U-001');await page.getByRole('option',{name:'张明 · U-001',exact:true}).click();await page.getByRole('button',{name:'应用查询',exact:true}).click();
  await page.locator('#query-range').click();if(width>=768){await tag('owner-validity').click();}else{await page.goBack();await page.locator('#validity-name').waitFor();}await page.waitForFunction(()=>!document.querySelector('[data-slot="popover-content"]'));assert.equal(await page.locator('#validity-name').inputValue(),'负责人草稿');assert.match(await page.locator('#form-owner-selected').textContent(),/U-002/);await nav('组合查询');assert.match(await page.locator('#applied-query').textContent(),/U-001/);
  await reset(page);await reset(page);assert.equal(await tag('owner-validity').count(),0);await nav('负责人及有效期表单');assert.equal(await page.locator('#validity-name').inputValue(),'');await page.reload();assert.equal(await page.locator('#validity-name').inputValue(),'');
 });
 await check('W12-strict-entry-history',async()=>{
  await go('exceptions','multi-step');await page.locator('#name').fill('历史草稿');await nav('查询与详情');await page.goBack();assert.equal(await page.locator('#name').inputValue(),'历史草稿');await page.goForward();await page.locator('#keyword').waitFor();
  for(const query of ['?page=','?page=unknown','?page=multi-step&page=list-detail','?other=x']){await page.goto(entry('workspace').replace('#scenario=primary',query+'#scenario=primary'));await page.getByRole('alert').waitFor();}
  await go('unknown');await page.getByRole('alert').waitFor();await go();await page.locator('#keyword').waitFor();
 });
 await check('W13-W14-T07-offline-layout-reset',async()=>{await go();await layout(page);assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);await capture('workspace');});
});
