from pathlib import Path
import json
E=Path('/Users/zhudaoming/Projects/yss-spec-project-template/.template-source/evidence/maintenance/2026-09-29-prototype-design-enhancement')
P=E/'pilot'
obs=json.loads((P/'observations.json').read_text()); audits=json.loads((P/'browser-report.json').read_text())
by={(x['task'],x['side']):x for x in audits};tasks={}
for x in obs:
 task=tasks.setdefault(x['task'],{'id':x['task'],'title':x['title'],'sides':{}});a=by.get((x['task'],x['side']),{})
 task['sides'][x['side']]={'status':'运行超时；文件集合未被评测器判定完成' if x['timeout'] else x['automatic_result'],'html':x['html_exists'],'design':x['design_exists'],'missing_resources':a.get('missing_resources',[]),'views':[{k:o[k] for k in ['scene','width','height','screenshot','overflow']}|{'error_count':len(o['issues'])} for o in a.get('observations',[])]}
(P/'review-data.js').write_text('window.PILOT_REVIEW = '+json.dumps(list(tasks.values()),ensure_ascii=False).replace('<','\\u003c')+';\n')
(P/'index.html').write_text('''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>六组匿名 A/B 试点记录</title><link rel="stylesheet" href="../examples/tokens.css"><link rel="stylesheet" href="review.css"><script src="review-data.js" defer></script><script src="review.js" defer></script></head><body><header><h1>六组匿名 A/B 试点记录</h1><p>真实 Agent 留存产物。超时、缺失和未完成资源如实展示；截图可查看，不代表可运行或质量通过。教学示例未用于补样。</p><div class="controls"><label>任务<select id="task"></select></label><label>候选<select id="side"><option>A</option><option>B</option></select></label><label>场景<select id="scene"></select></label><label>视口<select id="width"><option value="1440">1440×900</option><option value="390">390×844</option></select></label><a id="link">稳定链接</a></div><p id="status" role="status"></p><p id="error" role="alert" hidden></p><p><a id="draft" hidden>打开原始草案</a> <a href="../pilot-report.md">试点结论与验证边界</a></p><p>截图按原始像素显示；宽图可横向查看。仅有完整、同场景且行为正确的两侧才能用于视觉质量确认。</p></header><main id="view"></main><script></script></body></html>''')
(P/'review.css').write_text(''':root{font:var(--brand-font-size)/var(--brand-line-height) var(--brand-font-family);color:var(--brand-color-text);background:var(--brand-color-bg-layout)}*{box-sizing:border-box}body{margin:0}header{padding:var(--brand-size);background:var(--brand-color-bg-container)}h1{font-size:var(--brand-font-size-xl)}.controls{display:flex;gap:var(--brand-size);flex-wrap:wrap}label{display:flex;align-items:center;gap:var(--brand-size-xs)}select{font:inherit;min-height:var(--yss-control-height);max-width:100%}p{overflow-wrap:anywhere}a{color:var(--yss-color-primary-control)}:focus-visible{outline:2px solid var(--yss-color-primary-control);outline-offset:2px}main{overflow:auto}main img{display:block;max-width:none}main p{padding:var(--brand-size-lg)}#error{color:var(--brand-color-error)}''')
(P/'review.js').write_text('''(()=>{const $=id=>document.getElementById(id),data=window.PILOT_REVIEW;for(const t of data)$('task').add(new Option(t.title,t.id));function fail(message){$('error').textContent=message;$('error').hidden=false;$('view').replaceChildren();$('draft').hidden=true;$('status').textContent='';}function render(){const p=new URLSearchParams(location.hash.slice(1)),t=data.find(t=>t.id===(p.get('task')||data[0].id)),side=p.get('side')||'A',width=Number(p.get('width')||1440),scene=p.get('scene')||'primary';if(!t||!['A','B'].includes(side)||![1440,390].includes(width)){fail('对照链接无效。');return;}const r=t.sides[side];$('task').value=t.id;$('side').value=side;$('width').value=String(width);const scenes=[...new Set(Object.values(t.sides).flatMap(r=>r.views.map(v=>v.scene)))];if(!scenes.length)scenes.push('primary');$('scene').replaceChildren(...scenes.map(s=>new Option(s,s)));if(!scenes.includes(scene)){fail('场景不存在。');return;}$('scene').value=scene;$('error').hidden=true;$('view').replaceChildren();$('draft').hidden=true;const fragment=new URLSearchParams({task:t.id,side,scene,width}).toString();$('link').href='#'+fragment;if(!r){$('status').textContent='该次运行尚未收集。';return;}$('status').textContent=r.status+'；HTML '+(r.html?'已留存':'缺失')+'；设计说明 '+(r.design?'已留存':'缺失')+(r.missing_resources.length?'；缺失资源：'+r.missing_resources.join('、'):'');$('draft').hidden=!r.html;$('draft').href='ab/'+t.id+'/'+side+'/index.html#scenario='+scene;const v=r.views.find(v=>v.scene===scene&&v.width===width);if(v){const img=document.createElement('img');img.src='ab/'+t.id+'/'+side+'/'+v.screenshot;img.alt=t.title+' '+side+' '+scene+' '+width;img.width=v.width;img.height=v.height;$('view').append(img);$('status').textContent+='；该视口浏览器错误 '+v.error_count+'，整体横向溢出 '+(v.overflow?'有':'无');}else{const note=document.createElement('p');note.textContent='无可展示的真实截图；未用示例或人工页面替代。';$('view').append(note);}}function select(){const taskChanged=new URLSearchParams(location.hash.slice(1)).get('task')!==$('task').value;location.hash=new URLSearchParams({task:$('task').value,side:$('side').value,scene:taskChanged?'primary':$('scene').value,width:$('width').value}).toString();}for(const id of ['task','side','scene','width'])$(id).onchange=select;window.onhashchange=render;render();})();''')
print('six-task review index updated')
