from pathlib import Path
import subprocess,json,yaml,re,hashlib,socket,os
OUT=Path(__file__).resolve().parent;ROOT=Path('/private/var/folders/8d/60y8vj2j0nn37t4h26zbvvhw0000gn/T/yss-preview-pilot-20260912-0k_x_zmm');backend=ROOT/'backend';private=ROOT/'runtime-private';creds=json.loads((private/'database.json').read_text());docker=['docker','--context','desktop-linux'];records=[]
def sql(db,body,ref):
 p=subprocess.run(docker+['exec','-i','yss-preview-0kxzmm-pg','psql','-U','pilot','-d',db,'-v','ON_ERROR_STOP=1'],input=body,capture_output=True,text=True)
 records.append({'ref':str(ref),'database':db,'sha256':hashlib.sha256(body.encode()).hexdigest(),'exit_code':p.returncode,'stdout':p.stdout,'stderr':p.stderr});(OUT/'database-setup.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n');assert p.returncode==0,p.stderr
sql('pilot_control','CREATE TABLE leaf_alloc (biz_tag varchar(128) PRIMARY KEY,max_id numeric(20,0) NOT NULL,step numeric(11,0) NOT NULL,description varchar(256),update_time varchar(64));','synthetic leaf table matches checked source DDL')
for group,db in [('control','pilot_control'),('batch','pilot_control'),('targetdb','pilot_target')]:
 paths=sorted((backend/'db/file-sync'/group/'postgresql').glob('V*.sql'),key=lambda x:tuple(map(int,re.match(r'V([0-9.]+)',x.name).group(1).split('.'))))
 for p in paths:sql(db,p.read_text(),p.relative_to(backend))
seed='''CREATE TABLE pilot_preview_rows(id bigint PRIMARY KEY, label varchar(64), start_date timestamp NOT NULL, end_date timestamp);\nINSERT INTO pilot_preview_rows VALUES (1,'current-example','2026-01-01',NULL),(2,'historical-example','2025-01-01','2025-12-31');\nCREATE TABLE pilot_preview_empty(LIKE pilot_preview_rows INCLUDING ALL);\n''';(OUT/'target-seed.sql').write_text(seed);sql('pilot_target',seed,'target-seed.sql')
rows=[]
for i,(code,table) in enumerate([('PILOT_PREVIEW','pilot_preview_rows'),('PILOT_EMPTY','pilot_preview_empty')],1):
 config={'schemaVersion':1,'source':{'locationRef':'pilot-inbox','includeGlob':'*.csv','format':'CSV'},'mapping':{'columns':[{'source':'id','target':'id'}]},'target':{'dataSourceRef':'target','schema':'public','table':table},'mode':{'type':'HISTORICAL','effectiveDateColumn':'start_date','expiryDateColumn':'end_date'}}
 rows.append("INSERT INTO fs_sync_task(id,task_code,task_name,task_status,published_version,owner_id) VALUES (%d,'%s','synthetic preview','ACTIVE',0,'pilot');"%(i,code));rows.append("INSERT INTO fs_sync_task_draft(id,task_id,revision,config_json) VALUES (%d,%d,1,'%s');"%(100+i,i,json.dumps(config,separators=(',',':'))))
seed='\n'.join(rows)+'\n';(OUT/'control-seed.sql').write_text(seed);sql('pilot_control',seed,'control-seed.sql')
pgport=subprocess.check_output(docker+['port','yss-preview-0kxzmm-pg','5432'],text=True).strip().split(':')[-1];redisport=int(subprocess.check_output(docker+['port','yss-preview-0kxzmm-redis','6379'],text=True).strip().split(':')[-1])
sock=socket.socket();sock.bind(('127.0.0.1',0));port=sock.getsockname()[1];sock.close()
def ds(db):return {'url':'jdbc:postgresql://127.0.0.1:'+pgport+'/'+db,'username':'pilot','password':creds['password'],'driver-class-name':'org.postgresql.Driver','hikari':{'minimum-idle':0,'maximum-pool-size':4}}
inbox=private/'inbox';inbox.mkdir(exist_ok=True)
config={'server':{'address':'127.0.0.1','port':port},'spring':{'application':{'name':'yss-preview-pilot'},'main':{'allow-bean-definition-overriding':True,'lazy-initialization':True},'cloud':{'bootstrap':{'enabled':False},'discovery':{'enabled':False},'nacos':{'config':{'enabled':False},'discovery':{'enabled':False}}},'datasource':{'primary':ds('pilot_control'),'target':ds('pilot_target')},'redis':{'host':'127.0.0.1','port':redisport},'batch':{'job':{'enabled':False},'jdbc':{'initialize-schema':'never'}}},'eureka':{'client':{'enabled':False}},'yss':{'file-sync':{'enabled':True,'node-id':'pilot-preview','control-data-source':ds('pilot_control'),'locations':{'pilot-inbox':str(inbox)},'target-data-sources':{'target':'target'},'target-data-source-types':{'target':'POSTGRESQL'},'target-schemas':{'target':'public'}},'mybatis':{'db-type':'postgresql','mapper-location':'classpath*:mappers/**/*.xml','pageInterceptor':{'helperDialect':'postgresql'}},'leaf':{'leafSegmentEnable':True,'segment':{'database-type':'postgresql'}},'cache':{'active-type':'redis'}},'mybatis-plus':{'mapper-locations':'classpath*:mappers/**/*.xml'},'db-scheduler':{'enabled':False},'data-push':{'enabled':False,'features':{'schedule-enabled':False}},'ops':{'enabled':False},'transfer':{'worker':{'leader':{'enabled':False}}},'valuation':{'features':{'parse-queue-observer':{'enabled':False}},'workflow-plan-queue-observer':{'enabled':False},'product-taskflow-plan':{'enabled':False},'local-storage-root':str(private/'storage')},'management':{'endpoints':{'enabled-by-default':False}}}
cfg=private/'pilot-application.yml';cfg.write_text(yaml.safe_dump(config,allow_unicode=True));cfg.chmod(0o600)
logback=private/'pilot-logback.xml';logback.write_text('<configuration><appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender"><encoder><pattern>%date %-5level %logger - %msg%n</pattern></encoder></appender><root level="INFO"><appender-ref ref="CONSOLE"/></root></configuration>')
profile=private/'local-only.sb';profile.write_text('(version 1)\n(allow default)\n(deny network*)\n(allow network-outbound (remote ip "localhost:*"))\n(allow network-inbound (local ip "localhost:*"))\n')
jar=backend/'valuation-outsourced-starter/target/valuation-outsourced-starter-3.0.0-SNAPSHOT.jar';argv=['/usr/bin/sandbox-exec','-f',str(profile),'java','-Dspring.cloud.bootstrap.enabled=false','-Dspring.cloud.nacos.config.enabled=false','-Dspring.cloud.nacos.discovery.enabled=false','-jar',str(jar),'--spring.config.location=file:'+str(cfg),'--logging.config=file:'+str(logback)]
log=private/'java-start-01.raw.log';fd=log.open('w');proc=subprocess.Popen(argv,cwd=private,stdout=fd,stderr=subprocess.STDOUT,start_new_session=True);fd.close();(OUT/'service-launch.json').write_text(json.dumps({'pid':proc.pid,'argv':argv,'port':port,'config_ref':str(cfg),'raw_log_ref':str(log),'jar_sha256':hashlib.sha256(jar.read_bytes()).hexdigest(),'status':'starting','constraints':'outbound/inbound local-only sandbox profile; explicit config replaces defaults; original business source'},indent=2)+'\n');print('started pid',proc.pid,'port',port)
