import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),{chromium,webkit}=await import(process.env.YSS_PLAYWRIGHT_MODULE||'playwright'),rows=[];
for(const [engine,type] of [['chromium',chromium],['webkit',webkit]]){const browser=await type.launch({headless:true});try{for(const width of [1440,390])for(const mode of ['standard','glass']){
 console.log(JSON.stringify({engine,width,mode}));const c=await browser.newContext({viewport:{width,height:width===1440?900:844}});if(engine==='chromium')await c.setOffline(true);await c.route(/^https?:/,r=>r.abort());const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.text());});
 const url=pathToFileURL(path.join(here,'comparisons/list-detail/variants',mode,'index.html')).href;await p.goto(url);const trigger=p.getByRole('combobox',{name:'状态',exact:true});await trigger.waitFor();assert.equal(await trigger.getAttribute('data-slot'),'select-trigger');assert.equal(await p.locator('select#status').count(),0);
 // Keyboard selection must filter and reset pagination, with focus returning to the trigger.
 await p.getByRole('button',{name:'下一页',exact:true}).click();await trigger.focus();await p.keyboard.press('Enter');await p.getByRole('listbox').waitFor();await p.waitForFunction(()=>document.activeElement.getAttribute('role')==='option'&&document.activeElement.textContent==='全部状态');await p.keyboard.press('ArrowDown');await p.waitForFunction(()=>document.activeElement.textContent==='待核对');await p.keyboard.press('Enter');await p.waitForFunction(()=>document.activeElement.id==='status');await p.getByRole('button',{name:'查看 M-002',exact:true}).waitFor();assert.equal(await p.locator('tbody tr').count(),1);await p.getByText('第 1 页 / 共 1 页',{exact:true}).waitFor();
 await p.getByRole('button',{name:'重置筛选',exact:true}).click();await trigger.click();const popup=p.getByRole('listbox');await popup.waitFor();const rect=await popup.boundingBox(),tr=await p.locator('#status').boundingBox();assert(rect.x>=0&&rect.x+rect.width<=width+1);assert(Math.abs(rect.width-tr.width)<=2);
 const computed=await popup.evaluate(el=>{const s=getComputedStyle(el);return{fontSize:s.fontSize,blur:s.backdropFilter||s.webkitBackdropFilter,background:s.backgroundColor};});assert.equal(computed.fontSize,'14px');assert.equal(computed.blur!=='none',mode==='glass');if(engine==='chromium')await p.screenshot({path:path.join(here,'screenshots',`select-${mode}-${width}.png`),fullPage:true});
 await p.keyboard.press('Escape');await p.waitForFunction(()=>document.activeElement.id==='status');await trigger.click();await p.getByRole('option',{name:'已更新',exact:true}).click();assert.equal(await p.locator('tbody tr').count(),2);assert.equal(await p.getByRole('button',{name:'查看 M-002',exact:true}).count(),0);
 await p.getByText('评审工具：场景与辅助显示',{exact:true}).click();await p.locator('#reset').click();await p.getByRole('combobox',{name:'状态',exact:true}).waitFor();assert((await p.locator('#status').textContent()).includes('全部状态'));assert.equal(await p.getByRole('listbox').count(),0);
 if(mode==='glass'){await p.locator('#solid-surfaces').check();await trigger.click();assert.equal(await p.getByRole('listbox').evaluate(el=>getComputedStyle(el).backdropFilter||getComputedStyle(el).webkitBackdropFilter),'none');await p.keyboard.press('Escape');}
 assert.deepEqual(errors,[]);rows.push({engine,width,mode,status:'passed',computed,rect,trigger:tr});await c.close();
 }}finally{await browser.close();}}
// The same contract fails on the archived native control: evidence of the reported mismatch.
const browser=await chromium.launch({headless:true});try{const p=await browser.newPage();await p.goto(pathToFileURL(path.join(here,'revisions/v1-native-select/comparisons/list-detail/variants/glass/index.html')).href);await p.locator('#status').waitFor();const old=await p.locator('#status').evaluate(el=>({tag:el.tagName,slot:el.getAttribute('data-slot')}));assert.equal(old.tag,'SELECT');assert.equal(old.slot,null);rows.push({check:'v1-native-counterexample',expectedContract:'shadcn select-trigger',actual:old,status:'reproduced'});}finally{await browser.close();}
await writeFile(path.join(here,'evidence/select-v2.json'),JSON.stringify({status:'passed',rows},null,2));console.log(JSON.stringify({status:'passed',checks:rows.length}));
