BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL TIME ZONE 'UTC';
SET LOCAL statement_timeout='2s';
SELECT jsonb_build_object('id','fs_sync_task_columns','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(a.attnum::text, a.attname, pg_catalog.format_type(a.atttypid,a.atttypmod), a.attnotnull, pg_catalog.pg_get_expr(d.adbin,d.adrelid), pg_catalog.col_description(c.oid,a.attnum))::text AS canonical_value
FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
WHERE n.nspname='public' AND c.relname='fs_sync_task' AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','fs_sync_task_primary_key','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(con.conname, array_agg(a.attname ORDER BY k.ordinality))::text AS canonical_value
FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY k(attnum,ordinality) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum
WHERE n.nspname='public' AND c.relname='fs_sync_task' AND con.contype='p' GROUP BY con.conname ORDER BY con.conname COLLATE "C" LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','fs_sync_task_draft_columns','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(a.attnum::text, a.attname, pg_catalog.format_type(a.atttypid,a.atttypmod), a.attnotnull, pg_catalog.pg_get_expr(d.adbin,d.adrelid), pg_catalog.col_description(c.oid,a.attnum))::text AS canonical_value
FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
WHERE n.nspname='public' AND c.relname='fs_sync_task_draft' AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','fs_sync_task_draft_primary_key','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(con.conname, array_agg(a.attname ORDER BY k.ordinality))::text AS canonical_value
FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY k(attnum,ordinality) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum
WHERE n.nspname='public' AND c.relname='fs_sync_task_draft' AND con.contype='p' GROUP BY con.conname ORDER BY con.conname COLLATE "C" LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','fs_sync_task_version_columns','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(a.attnum::text, a.attname, pg_catalog.format_type(a.atttypid,a.atttypmod), a.attnotnull, pg_catalog.pg_get_expr(d.adbin,d.adrelid), pg_catalog.col_description(c.oid,a.attnum))::text AS canonical_value
FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
WHERE n.nspname='public' AND c.relname='fs_sync_task_version' AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','fs_sync_task_version_primary_key','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(con.conname, array_agg(a.attname ORDER BY k.ordinality))::text AS canonical_value
FROM pg_catalog.pg_constraint con JOIN pg_catalog.pg_class c ON c.oid=con.conrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace CROSS JOIN LATERAL unnest(con.conkey) WITH ORDINALITY k(attnum,ordinality) JOIN pg_catalog.pg_attribute a ON a.attrelid=c.oid AND a.attnum=k.attnum
WHERE n.nspname='public' AND c.relname='fs_sync_task_version' AND con.contype='p' GROUP BY con.conname ORDER BY con.conname COLLATE "C" LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','populated_task','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(t.id::text,t.task_code,t.task_name,t.task_status,t.published_version::text,t.owner_id,t.snapshot_retention_days::text,to_char(t.gmt_create,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(t.gmt_modified,'YYYY-MM-DD"T"HH24:MI:SS.US'))::text AS canonical_value FROM public.fs_sync_task t WHERE t.task_code='PILOT_PREVIEW' ORDER BY t.id LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','populated_draft','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(d.id::text,d.task_id::text,d.revision::text,d.config_json,d.validation_config_digest,d.validation_environment_digest,to_char(d.validated_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(d.validation_expires_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(d.gmt_create,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(d.gmt_modified,'YYYY-MM-DD"T"HH24:MI:SS.US'))::text AS canonical_value FROM public.fs_sync_task_draft d JOIN public.fs_sync_task t ON t.id=d.task_id WHERE t.task_code='PILOT_PREVIEW' ORDER BY d.id LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','populated_versions','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(v.id::text,v.task_id::text,v.version_number::text,v.config_digest,v.config_json,to_char(v.gmt_create,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(v.gmt_modified,'YYYY-MM-DD"T"HH24:MI:SS.US'))::text AS canonical_value FROM public.fs_sync_task_version v JOIN public.fs_sync_task t ON t.id=v.task_id WHERE t.task_code='PILOT_PREVIEW' ORDER BY v.version_number,v.id LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','empty_task','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(t.id::text,t.task_code,t.task_name,t.task_status,t.published_version::text,t.owner_id,t.snapshot_retention_days::text,to_char(t.gmt_create,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(t.gmt_modified,'YYYY-MM-DD"T"HH24:MI:SS.US'))::text AS canonical_value FROM public.fs_sync_task t WHERE t.task_code='PILOT_EMPTY' ORDER BY t.id LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','empty_draft','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(d.id::text,d.task_id::text,d.revision::text,d.config_json,d.validation_config_digest,d.validation_environment_digest,to_char(d.validated_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(d.validation_expires_at,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(d.gmt_create,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(d.gmt_modified,'YYYY-MM-DD"T"HH24:MI:SS.US'))::text AS canonical_value FROM public.fs_sync_task_draft d JOIN public.fs_sync_task t ON t.id=d.task_id WHERE t.task_code='PILOT_EMPTY' ORDER BY d.id LIMIT 1001) fixed_query;
SELECT jsonb_build_object('id','empty_versions','rows',coalesce(jsonb_agg(canonical_value),'[]'::jsonb))::text FROM (SELECT jsonb_build_array(v.id::text,v.task_id::text,v.version_number::text,v.config_digest,v.config_json,to_char(v.gmt_create,'YYYY-MM-DD"T"HH24:MI:SS.US'),to_char(v.gmt_modified,'YYYY-MM-DD"T"HH24:MI:SS.US'))::text AS canonical_value FROM public.fs_sync_task_version v JOIN public.fs_sync_task t ON t.id=v.task_id WHERE t.task_code='PILOT_EMPTY' ORDER BY v.version_number,v.id LIMIT 1001) fixed_query;
ROLLBACK;
