<script setup lang="ts">
import { ref, computed, nextTick } from 'vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader } from '@/components/ui/dialog'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from '@/components/ui/alert-dialog'
import { Field, FieldLabel, FieldDescription } from '@/components/ui/field'
import { Separator } from '@/components/ui/separator'
import Notice from './Notice.vue'
import { useWorkspacePage } from './workspace-page'
const props=defineProps<{scene:any}>()
const rows=ref(props.scene.data.rows),query=ref(''),filter=ref(''),dialog=ref(false),kind=ref('detail'),draft=ref<any>(null),error=ref(''),reloaded=ref(false),feedback=ref(''),confirmReload=ref(false)
const baseline=ref(''),ownerOpen=ref(false)
const dirty=computed(()=>kind.value==='edit'&&!!draft.value&&JSON.stringify(draft.value)!==baseline.value)
const workspace=useWorkspacePage()
workspace.trackDirty(dirty)
workspace.onLeave(()=>{dialog.value=false;confirmReload.value=false;ownerOpen.value=false})
let origin:HTMLElement|null=null
const visible=computed(()=>rows.value.filter((x:any)=>(x.id+x.name).includes(filter.value)))
function open(row:any,mode:string,e:Event){origin=e.currentTarget as HTMLElement;if(dirty.value){dialog.value=true;feedback.value='未提交草稿已保留，请先继续处理。';return}draft.value={...row};baseline.value=JSON.stringify(draft.value);kind.value=mode;error.value='';reloaded.value=false;dialog.value=true}
function save(retry=false){if(props.scene.id==='no-permission')return;if(!draft.value.name.trim()){error.value='请输入资料名称';document.getElementById('name')?.focus();return}if(props.scene.id==='failure'&&!retry){error.value='保存失败，输入已保留，请重试。';return}if(props.scene.id==='conflict'&&!reloaded.value){error.value='资料已更新。输入已保留，重新加载前可复制内容。';return}rows.value=rows.value.map((row:any)=>row.id===draft.value.id?{...draft.value,status:'已更新'}:row);baseline.value=JSON.stringify(draft.value);dialog.value=false;feedback.value='保存成功（本地模拟）。'}
function reload(){draft.value={...props.scene.data.server_rows.find((row:any)=>row.id===draft.value.id)};baseline.value=JSON.stringify(draft.value);reloaded.value=true;confirmReload.value=false;error.value='已重新加载，请确认后保存。'}
function editFocus(e:Event){if(kind.value==='edit'){e.preventDefault();nextTick(()=>{if(workspace.active.value)document.getElementById('name')?.focus()})}}
function returnFocus(e:Event){e.preventDefault();workspace.active.value&&origin?.isConnected&&origin.focus()}
function reloadFocus(e:Event){e.preventDefault();workspace.active.value&&document.getElementById(reloaded.value?'save':'reload')?.focus()}
</script>
<template><Notice v-if="dirty&&!dialog" class="draft-resume">有未提交的资料草稿。<Button variant="outline" @click="dialog=true">继续编辑草稿</Button></Notice><section class="surface" aria-label="查询条件"><form @submit.prevent="filter=query.trim()"><Label for="keyword">资料名称</Label><div class="actions"><Input id="keyword" v-model="query" placeholder="输入名称或编号"/><Button type="submit">查询</Button><Button type="button" variant="outline" @click="query='';filter=''">重置筛选</Button></div></form></section><section class="surface" aria-label="资料列表"><h2>资料列表 · 共 {{visible.length}} 条</h2><Notice v-if="scene.id==='no-permission'">当前资料仅可查看。</Notice><Table class="responsive-list"><TableHeader><TableRow><TableHead v-for="text in ['编号','资料名称','负责人','状态','操作']" :key="text">{{text}}</TableHead></TableRow></TableHeader><TableBody><TableRow v-for="row in visible" :key="row.id"><TableCell data-label="编号">{{row.id}}</TableCell><TableCell data-label="资料名称">{{row.name}}</TableCell><TableCell data-label="负责人">{{row.owner}}</TableCell><TableCell data-label="状态"><Badge variant="secondary">{{row.status}}</Badge></TableCell><TableCell><div class="row-actions"><Button variant="outline" :aria-label="`查看 ${row.id}`" @click="e=>open(row,'detail',e)">查看</Button><Button variant="outline" :aria-label="`编辑 ${row.id}`" :disabled="scene.id==='no-permission'" @click="e=>open(row,'edit',e)">编辑</Button></div></TableCell></TableRow><TableRow v-if="!visible.length"><TableCell :colspan="5"><p role="status">{{scene.id==='loading'?'正在加载（固定评审状态）':'暂无符合条件的资料'}}</p></TableCell></TableRow></TableBody></Table></section><p role="status">{{feedback}}</p>
<Dialog v-model:open="dialog"><DialogContent :show-close-button="false" @open-auto-focus="editFocus" @close-auto-focus="returnFocus"><DialogHeader><DialogTitle>{{kind==='detail'?'资料详情':'编辑资料'}}</DialogTitle><DialogDescription>{{kind==='detail'?'核对当前资料信息。':'修改名称或负责人后保存。'}}</DialogDescription></DialogHeader><template v-if="draft"><template v-if="kind==='detail'"><dl><template v-for="(v,k) in draft" :key="k"><dt>{{({id:'编号',name:'名称',owner:'负责人',status:'状态',version:'版本'})[k]}}</dt><dd>{{v}}</dd></template></dl><Button variant="outline" @click="dialog=false">关闭详情</Button></template><form v-else @submit.prevent="save()" novalidate><Field :data-invalid="error==='请输入资料名称'"><FieldLabel for="name">资料名称</FieldLabel><Input id="name" v-model="draft.name" :maxlength="80" required :aria-invalid="error==='请输入资料名称'" :aria-describedby="error?'name-help edit-error':'name-help'" @update:model-value="error==='请输入资料名称'&&(error='')"/><FieldDescription id="name-help">草稿保留至保存成功或确认放弃；重新加载会替换完整资料。</FieldDescription></Field><Field><FieldLabel for="owner">负责人</FieldLabel><Select v-model="draft.owner" v-model:open="ownerOpen"><SelectTrigger id="owner"><SelectValue/></SelectTrigger><SelectContent><SelectItem v-for="owner in ['张明','李华','王宁','最新负责人']" :key="owner" :value="owner">{{owner}}</SelectItem></SelectContent></Select></Field><Separator/><p>版本：<span id="version">{{draft.version}}</span></p><Notice v-if="error" id="edit-error" error>{{error}}</Notice><div class="actions"><Button id="save" type="submit">保存</Button><Button v-if="error&&scene.id==='failure'" id="retry" type="button" variant="outline" @click="save(true)">重试</Button><Button v-if="error&&scene.id==='conflict'" id="reload" type="button" variant="outline" @click="confirmReload=true">重新加载</Button><Button type="button" variant="outline" @click="dialog=false">取消</Button></div></form></template></DialogContent></Dialog>
<AlertDialog v-model:open="confirmReload"><AlertDialogContent @close-auto-focus="reloadFocus"><AlertDialogHeader><AlertDialogTitle>放弃本地修改并重新加载？</AlertDialogTitle><AlertDialogDescription>本地草稿将被服务端完整快照替换；取消可保留当前输入。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>保留草稿</AlertDialogCancel><AlertDialogAction @click="reload">放弃并重新加载</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></template>
