#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const load = ref => JSON.parse(readFileSync(new URL(ref, import.meta.url), 'utf8'));
const schema = load('../references/technical-design-common.schema.json');
const branches = [
  ['domain-driven', '../../yss-tactical-design/references/tactical-design.schema.json'],
  ['layered-mvc', '../../yss-mvc-design/references/mvc-design.schema.json']
];
schema.$comment = 'Generated by scripts/generate-schema.mjs from common and specialist schemas. Do not hand-edit.';
schema.allOf = branches.map(([family, ref]) => {
  const branch = load(ref); delete branch.$id; delete branch.$schema;
  return { if: { properties: { architecture: { properties: { family: { const: family } } } } }, then: { properties: { design: branch } } };
});
const output = fileURLToPath(new URL('../references/technical-design.schema.json', import.meta.url));
const bytes = `${JSON.stringify(schema, null, 2)}\n`;
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== bytes) throw new Error('技术设计 Schema 投影漂移，请运行 generate-schema.mjs');
} else writeFileSync(output, bytes);
process.stdout.write('技术设计分支 Schema 已同步\n');
