#!/usr/bin/env node
export {
  REPOSITORY_SCOPES as scopes,
  LAYOUT_POLICIES as layoutPolicies,
  GITLINK_MODE as gitlinkMode,
  violationRepositoryScope as violation,
  validRepositoryScope as valid,
  gitSubmoduleScaffoldViolation as scaffoldViolation,
  isGitSubmoduleMount as isMount
} from "./lib/repository-scope-policy.mjs";
