import {React,useState,render,Notice,Button,Input,Label,Badge,Checkbox,Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetFooter,SheetClose,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,Pagination,PaginationContent,PaginationItem,Empty,EmptyHeader,EmptyTitle,EmptyDescription,Spinner,Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from './shared';
function Page({scene}){
 const origin=React.useRef(null),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('asc'),[page,setPage]=useState(0),[selected,setSelected]=useState([]),[detail,setDetail]=useState(null);
 const rows=scene.data.rows.filter(r=>(r.name+r.id).includes(query)&&(status==='all'||r.status===status)).sort((a,b)=>sort==='asc'?a.id.localeCompare(b.id):b.id.localeCompare(a.id));
 const size=2,visible=rows.slice(page*size,page*size+size),pages=Math.max(1,Math.ceil(rows.length/size)),readonly=scene.id==='no-permission';
 const toggle=id=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);
 function open(row,trigger){origin.current=trigger;setDetail(row);}
 return <><section className="surface filter-surface"><div className="section-heading"><h2>查询条件</h2><span className="muted">组合条件即时生效</span></div><div className="filters query-filters"><div><Label htmlFor="keyword">资料名称或编号</Label><Input id="keyword" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div><div><Label htmlFor="status">状态</Label><select id="status" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="all">全部状态</option><option>待核对</option><option>已更新</option></select></div><Button variant="outline" onClick={()=>{setQuery('');setStatus('all');setPage(0);}}>重置筛选</Button></div></section>
 <section className="surface results-surface"><div className="toolbar results-toolbar"><h2>资料列表 · 共 {rows.length} 条</h2><Button variant="outline" onClick={()=>setSort(sort==='asc'?'desc':'asc')}>编号{sort==='asc'?'降序':'升序'}</Button><span className={`selection-count ${selected.length?'has-selection':''}`} role="status">已选择 {selected.length} 项</span></div><p className="muted result-context">{query?`关键词：${query}；`:''}状态：{status==='all'?'全部':status}；选择跨页保留，重置场景清除。</p>{readonly&&<Notice>当前为只读；可查询和查看详情，不可选择处理。</Notice>}
 <Table className="responsive-list"><TableHeader><TableRow>{['选择','编号','资料名称','状态','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={row.id} data-state={selected.includes(row.id)?'selected':undefined}><TableCell><Checkbox aria-label={`选择 ${row.id}`} disabled={readonly} checked={selected.includes(row.id)} onCheckedChange={()=>toggle(row.id)}/></TableCell><TableCell data-label="编号">{row.id}</TableCell><TableCell data-label="资料名称">{row.name}</TableCell><TableCell data-label="状态"><Badge variant="secondary" className={row.status==='待核对'?'status-pending':'status-current'}><span className="status-dot" aria-hidden="true"/>{row.status}</Badge></TableCell><TableCell><div className="row-actions"><Button variant="outline" className="detail-action" aria-label={`查看 ${row.id}`} onClick={e=>open(row,e.currentTarget)}>查看详情</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" aria-label={`更多 ${row.id}`} id={`more-${row.id}`}>更多</Button></DropdownMenuTrigger><DropdownMenuContent align="end" onCloseAutoFocus={e=>{if(detail)e.preventDefault();}}><DropdownMenuItem onSelect={()=>open(row,document.getElementById(`more-${row.id}`))}>查看详情</DropdownMenuItem><DropdownMenuItem disabled>导出（未模拟）</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&(scene.id==='loading'?<Notice><Spinner aria-hidden="true"/>正在加载（固定评审状态）</Notice>:<Empty><EmptyHeader><EmptyTitle>暂无符合条件的资料</EmptyTitle><EmptyDescription>调整筛选条件或重置筛选后重试。</EmptyDescription></EmptyHeader></Empty>)}
 <Pagination aria-label="资料分页"><PaginationContent><PaginationItem><Button variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>上一页</Button></PaginationItem><PaginationItem><span aria-live="polite">第 {page+1} 页 / 共 {pages} 页</span></PaginationItem><PaginationItem><Button variant="outline" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>下一页</Button></PaginationItem></PaginationContent></Pagination></section>
 <Sheet open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><SheetContent showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();origin.current?.focus();}}><SheetHeader><SheetTitle>资料详情</SheetTitle><SheetDescription>核对选中资料；关闭后返回来源操作。</SheetDescription></SheetHeader>{detail&&<dl>{Object.entries(detail).map(([k,v])=><React.Fragment key={k}><dt>{({id:'编号',name:'资料名称',owner:'负责人',status:'状态',version:'版本'})[k]}</dt><dd>{v}</dd></React.Fragment>)}</dl>}<SheetFooter className="sheet-actions material-surface"><SheetClose asChild><Button variant="outline">关闭详情</Button></SheetClose></SheetFooter></SheetContent></Sheet></>;
}
render(Page,'查询与详情');
