import json, hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
OUT = Path(__file__).resolve().parent
rows = []
def add(id, title, priority, sources, trigger, chain, complexity, suggestion, constraints, verification, authority, propagation):
    refs=[]
    for filename, line in sources:
        p=ROOT/filename
        raw=p.read_bytes()
        assert 0 < line <= len(raw.splitlines()), (filename,line)
        refs.append(dict(path=filename,line=line,sha256=hashlib.sha256(raw).hexdigest()))
    rows.append(dict(id=id,title=title,priority=priority,status='static-candidate-unmeasured',sources=refs,trigger=trigger,call_chain=chain,complexity_or_repetition=complexity,suggestion=suggestion,semantic_constraints=constraints,verification_design=verification,authority=authority,propagation=propagation))

shared='本体 scripts/lib 为当前本体权威；4 个 harness 子仓同名实现需逐 hash/差异核对，不把同名等同同版本。'
spread='本体 → harness 子仓 scripts（具体同步合同待主控确认）→ 各 CLI snapshot/template → 生成实例；只改已确认权威源后按分发合同传播。'
add('P01','Schema 校验重复启动 Python','日常优先', [('scripts/lib/json-schema.mjs',20),('scripts/verify-context-reconciliation',36),('scripts/lib/plan-spec-entry.mjs',71),('scripts/lib/strategic-handoff-io.mjs',55)],'Plan entry、context reconciliation、审批/任务/交接 schema 校验','Plan entry → Node reconciliation CLI → Python jsonschema；其他库直接启动 Python','N 次验证支付 N 次 Python 启动/import/schema 构造；多个 schema 调用在一次开包中累计。','先拆分启动/import/验证耗时；同一次验证批量传多个 value/schema，或导出进程内 API 复用 Node 调用。Node schema 替代仅为更高成本备选。','保留 Draft202012、格式、错误排序、退出码、严格 YAML 和异常阻断；不跳 schema。','隔离副本运行 node scripts/verify-context-reconciliation-scenarios、node scripts/verify-plan-spec-entry-scenarios；对合法/非法 schema 全语料作输出和退出码差分；单条/100条比较进程数与总时长。',shared,spread)
add('P02','Context 唯一性扫描按调用重复','日常优先',[('scripts/lib/context-contract.mjs',26),('scripts/lib/context-contract.mjs',101),('scripts/lib/context-contract.mjs',191)],'每次 verifyContextSnapshot/parseContextContract','snapshot → parseContextContract → collectContextFiles → readdir/嵌套 Git 判断 → 根词汇解析','每次 O(目录项数＋词汇字节)，不是仅 referenced_terms_digest 的 hash；排除目录和嵌套 Git 已存在。','同一边界批量快照共享一次清单；将词汇纯解析成本与目录唯一性检查成本分开计时。','新增/移动嵌套 CONTEXT、大小写错误、CONTEXT-MAP、symlink、Git 边界变化必须失效；不能仅按根 CONTEXT hash 跨调用缓存。','node scripts/verify-context-contract-scenarios；node scripts/verify-context-reconciliation-scenarios；在10/1000/10000目录及新增嵌套词汇文件上比较扫描数/输出。',shared,spread)
add('P03','查询与验证调度粒度及反馈','日常/fast 优先',[('scripts/lib/lifecycle-context-query.mjs',65),('scripts/run-template-verification',23),('scripts/run-template-verification',35),('scripts/run-template-verification',111),('scripts/lib/template-verification.mjs',60)],'Agent 连续 route 查询；fast/candidate/release 聚合验证','query 每进程加载注册表/编排合同/技能注册表；runner 收集全工作树→映射/升级→组间并行→组内串行→末尾统一打印','查询每次 O(合同大小)；runner 已支持 1..4 并发，不是完全串行；未知/core改动升级 release 可能扩大成本；stdout/stderr 累积内存。','保持合并查询；记录每命令开始结束、即时输出耗时与失败；测量后将真正独立命令以受限并发编排。','不得伪造跨边界 Fresh Verification；未知路径保持 fail-closed；并行前确认共享写入、服务端口和清理；输出优化不自动等于执行提速。','node scripts/verify-lifecycle-context-query-scenarios；node scripts/verify-template-verification-scenarios；对固定 changed-files 比较 --plan JSON、最终退出码、顺序/错误；人工注入慢子命令检查即时进度。',shared,spread)
add('P04','技能投影重复源 hash 和单项 Git 探测','fast 优先',[('scripts/lib/skill-supply-chain.mjs',31),('scripts/lib/skill-supply-chain.mjs',119),('scripts/lib/skill-supply-chain.mjs',147),('scripts/lib/skill-supply-chain.mjs',165)],'sync-skills --check、update-skill-lock、实体投影同步','每个投影root×每个skill → treeHash(source/target)；部分条目 → git ls-files','最多六投影重复读源；symlink 正确目标分支已有快速判断。','单次调用 memoize canonical source hash；一次 git ls-files -z 构建 tracked 集；实体投影内容不变则避免无谓重拷贝需另测。','hash 归一化、排序、二进制行为、锁语义及 symlink 判定不变；同步模式和check模式分开；不信任mtime作为唯一新鲜度。','隔离副本 node scripts/sync-skills --check、node scripts/verify-skill-governance；实体/符号链接混合、删除、篡改、CRLF、未跟踪条目矩阵；统计 readFile/git调用数。',shared,spread)
add('P05','分发场景串行初始化和完整实例复制','全量优先',[('.template-source/scripts/verify-delivery-harness-distribution.mjs',23),('.template-source/scripts/verify-delivery-harness-distribution.mjs',52),('scripts/verify-frontend-delivery-scenarios',30),('docs/process/template-verification-profiles.yaml',265)],'完整模板分发回归','源场景一次；distribution → backend init → frontend init → 实例场景 → cpSync两实例','源/分发两种覆盖；初始化与拷贝按总文件字节/目录项；两边生成目前串行。','独立实例初始化受限并行；隔离 immutable fixture 复用；按阶段计时初始化、复制、门禁、服务场景。','源代码与生成实例来源不同不能直接删重复场景；不共享可变 fixture；保留丢失/篡改/错端阻断及服务清理。','仅隔离副本 node .template-source/scripts/verify-delivery-harness-distribution.mjs；node scripts/verify-frontend-delivery-scenarios；核对同一断言集、资源/服务回收、失败路径；冷/热文件缓存分开。','本体 .template-source/scripts 为分发测试权威，场景 scripts 另有实例副本。',spread)
add('P06','旧 CLI 隐式全量同步与多投影物化','完整验证/打包',[('submodules/create-yss-spec/package.json',26),('submodules/create-yss-spec/scripts/sync-template.js',302),('submodules/create-yss-spec/scripts/sync-template.js',342),('submodules/create-yss-spec/scripts/sync-template.js',357),('submodules/create-yss-harness-dev/package.json',25),('submodules/create-yss-strategic-design/package.json',25)],'三个旧 CLI 的 pretest/prepack；spec test:integration','package hook → sync-template → staging → 每skill每projection cpSync → update-skill-lock → snapshot替换','多投影放大IO；test不是纯只读；相邻test/pack可能重复相同输入同步。','显式区分“准备当前快照”和“验证已准备快照”；同输入复用临时快照，保留独立一致性check；先逐阶段测。','必须保留快照新鲜度、分发manifest、npm点文件编码、回滚；不能直接取消hook而允许陈旧发布；三旧CLI并非逐字同源。','在隔离三个CLI中分别计时 node scripts/sync-template.js 与 node --test 对应tests；核对snapshot/lock/编码文件字节和初始化结果；模拟替换失败验证回滚。','三个 CLI scripts/sync-template.js 各自为其当前实现；共同上游实现契约需明确。','模板/专用harness来源 → 各旧CLI sync-template.js → template与snapshot；不直接修改template副本。')
add('P07','专职 CLI syncCore 全仓归档与同步遍历','同步/打包',[('.template-source/cli-core/build.mjs',18),('.template-source/cli-core/build.mjs',79),('.template-source/cli-core/build.mjs',172),('submodules/create-yss-harness-backend/scripts/sync-core.mjs',2)],'新 backend/frontend CLI sync-core、sync-template（含 --check）','薄脚本 → vendor/cli-core/build → git archive整仓 → tar全量展开 → 取core子树或manifest选择 → inventory/capture','syncCore只需一子树却先O(整仓字节)归档；capture投影重复读取实体源；check也准备源快照。','syncCore精确git archive指定子树；syncTemplate按manifest确定可安全筛选的归档路径；单次capture共享实体字节/hash。','必须基于固定commit、保持路径/mode/manifest与相对symlink规则、投影循环拒绝；不能把未提交工作树混进固定commit。','隔离CLI执行 node scripts/sync-core.mjs <local-repo> <40-char-commit> --check；源core锁/字节/mode全等；无关大文件增长时测归档体积与RSS；sync-template需额外投影路径矩阵。','确定 canonical=.template-source/cli-core；CLI cli-core.lock.json sourcePath/sourceRevision声明来源。','本体 .template-source/cli-core → sync-core → 新CLI vendor/cli-core；template来源为各专职harness提交。')
add('P08','内容寻址 blob 读取端按逻辑路径重复 hash','CLI init/preview/verify-bundle',[('.template-source/cli-core/bundle.mjs',61),('.template-source/cli-core/bundle.mjs',71),('.template-source/cli-core/build.mjs',207)],'新 backend/frontend CLI装载快照，尤其六投影共享blob','构建以digest Map去重存储 → loadBundle逐snapshot.files逻辑路径读取相同blob/hash','实际O(逻辑路径字节总量)而不是O(unique blob字节)；相同bytes被多次Buffer分配。','一次loadBundle内以已验证digest缓存Buffer，逻辑路径仍各自校验；不得跨调用信任可变磁盘。','每逻辑路径governance/type/mode仍校验；同blob篡改立即阻断；调用方不得修改共享Buffer影响其他路径。','隔离副本专职CLI node scripts/verify-bundle.mjs；pnpm --dir .template-source/cli-core test；重复blob/篡改/模式差异/Buffer变异场景，比较read/hash次数和RSS。','确定 canonical=.template-source/cli-core/bundle.mjs；两个新CLI为锁定副本。','canonical → sync-core → vendor/cli-core → CLI执行；不改content-addressed格式。')
add('P09','交接包安全路径、文件树及嵌套包多次验证','交接/完整场景',[('scripts/lib/strategic-handoff-io.mjs',23),('scripts/lib/strategic-handoff-io.mjs',34),('scripts/lib/strategic-handoff.mjs',72),('scripts/lib/backend-delivery.mjs',80),('scripts/lib/backend-delivery.mjs',130),('scripts/lib/backend-delivery.mjs',147)],'战略/后端导出、导入、frontend joint acceptance','safe每级exists/lstat → files → treeDigest → schema；backend开包再验证嵌套战略包；导出/导入再开包验输出','文件数×平均目录深度的重复stat，以及同包多次解析/hash；小JSON还支付P01。','同一次不可变包处理共享目录清单、已读取字节和schema结果；按输入/输出边界保留重新验证。','安全路径、symlink禁止、未登记文件、审批/摘要/版本、导入前后完整性不能省；缓存必须防止包被外部改写。','隔离 node scripts/verify-strategic-handoff-package-scenarios 和 node scripts/verify-frontend-delivery-scenarios；目录深度/包规模矩阵与篡改/ZIP-slip拒绝；记录stat/hash/schema次数。',shared,spread)
add('P10','真实 Maven/pnpm 验证成本与执行时间边界','实现/脚手架，非普通Plan',[('.agents/skills/yss-ddd-scaffold-generator/scripts/run_scaffold_verification.mjs',60),('.agents/skills/yss-ddd-scaffold-generator/scripts/run_scaffold_verification.mjs',89),('.agents/skills/yss-frontend-scaffold-generator/scripts/run_scaffold_verification.mjs',22),('scripts/verify-scaffold-generator-scenarios',461),('.agents/skills/yss-frontend-scaffold-generator/scripts/scaffold-generator.test.mjs',26),('.agents/skills/yss-ddd-scaffold-generator/scripts/scaffold-generator.test.mjs',161),('.agents/skills/yss-layered-mvc-scaffold-generator/scripts/scaffold-generator.test.mjs',115)],'真实批准工程验证；条件开启的真实Maven测试','Maven validate→test→package；pnpm install→lint→type-check→build；root scenario/mock 与真实技能runner区别','外部JVM/依赖下载/构建占比未知；固定三阶段可能重复插件执行，但当前合同要求三命令；runner无自身timeout并缓冲输出。','单阶段计时＋脱敏流式日志；复用包管理器合法缓存；测冷/热依赖仓；条件fixture与真实集成单列。','不擅自合并Maven命令、skipTests、省install或改变验收；保留每命令退出码和证据；共享build输出禁止盲目并行。','有批准可用fixture后运行 node .agents/skills/yss-ddd-scaffold-generator/scripts/run_scaffold_verification.mjs --project-root <fixture> --evidence-dir <isolated-evidence>；前端同入口；记录工具版本/缓存/网络。当前没有真实依赖环境证据，不能以mock时间预测。','canonical技能脚本；layered MVC verification引用DDD共享runner；运行命令由scaffold合同固定。','canonical .agents/skills → Skill投影与锁 → harness/CLI → generated project；不执行或修改实际产品工程。')
add('P11','网络/外部命令耗时、现有commit缓存与超时','外部依赖，单列',[('scripts/lib/template-commit-cache.mjs',16),('scripts/lib/template-commit-cache.mjs',38),('scripts/lib/frontend-delivery.mjs',23),('.template-source/cli-core/update.mjs',5),('submodules/create-yss-spec/src/self-update.js',64)],'远程模板首次获取、真实服务revision探测、显式CLI self-update','缓存miss→git fetch depth1；hit→本地commit校验；frontend fetch timeout5s；newCLI npm命令timeout120s，旧CLI npm view30s','网络和包管理器自身重试不可由本地静态代码估计；commit cache已按repository＋commit复用，未见脚本自己反复重试。','按cache hit/miss及命令类别记录；fetch加可配置总时限/取消与临时目录清理；区分npm查询和安装预算；保留cache已有快路。','活服务revision不得用过时成功缓存替代；self-update不能自动运行以测性能；不得输出凭据；超时不等于更快成功。','node scripts/verify-template-cache-scenarios（local repo fixture）；网络使用本地延迟/断开fixture或注入spawn，核对超时、错误分类、清理；真实仓/服务成本待可用环境测量。',shared+' 新CLI canonical .template-source/cli-core；旧CLI src各自维护。',spread+' self-update源不通过scripts投影同一化。')
add('P12','前端模板复制范围与重复全树遍历','脚手架生成',[('.agents/skills/yss-frontend-scaffold-generator/scripts/generate_scaffold.mjs',22),('.agents/skills/yss-frontend-scaffold-generator/scripts/generate_scaffold.mjs',50),('.agents/skills/yss-frontend-scaffold-generator/scripts/generate_scaffold.mjs',58),('.agents/skills/yss-frontend-scaffold-generator/scripts/generate_scaffold.mjs',72)],'已批准模板checkout初始化前端工程','cpSync排除.git → walk全部输出替换占位符 → walk再次生成manifest','O(checkout总字节＋文件数)；只排.git，工作树若已有node_modules/dist会复制并参与遍历；>2MB仅跳替换，不跳复制。','基准使用干净固定commit checkout；研究基于批准文件清单导出与一次遍历生成manifest；阻止无关依赖缓存进入生成范围需合同化。','模板路径、commit/remote、替换规则、锁文件、用户批准输入均保留；不能静默排除模板有意包含文件；生成文件清单应与实际输出一致。','隔离 node scripts/verify-frontend-scaffold-generator-scenarios；干净/含缓存checkout、binary/>2MB、嵌套目录与占位符对照；比较manifest、文件字节和遍历次数。','canonical .agents/skills/yss-frontend-scaffold-generator/scripts；模板内容另有批准来源。','canonical Skill → 投影/锁/分发；只在清洁临时fixture生成。')

def extra_ref(c,path,line):
    raw=(ROOT/path).read_bytes();assert line<=len(raw.splitlines())
    c['sources'].append({'path':path,'line':line,'sha256':hashlib.sha256(raw).hexdigest()})
p8=next(c for c in rows if c['id']=='P08')
p8.update(title='CLI 事务持久化写放大；blob 去重为次级候选',priority='完整实例初始化：需协议级设计后优化',trigger='专职 backend/frontend CLI init/apply，数千逻辑文件',call_chain='applyTransaction逐operation → durable(progress.json) → durable(op.path)；每次durable执行临时文件fsync→rename→父目录fsync；更新已有文件先durable backup；入口loadBundle另按逻辑路径重读blob',complexity_or_repetition='新文件约4次fsync/operation，外加journal、身份记录；已有文件备份再增加。progress重复序列化createdDirectories且includes查重随目录增长。build内容寻址去重没有减少事务实际逻辑文件写。',suggestion='优先测每阶段与fsync总次数/等待、日志字节。设计一次持久化操作计划＋分批进度/WAL或初始化staging事务提交，先明确恢复不变量再实现；blob单次load内复用可作低风险次级优化。',semantic_constraints='不可直接删除fsync、批量并行写或缩减恢复记录；保留日志先行、文件/目录持久化、进程中断与崩溃恢复、身份/并发变化检查、用户文件保护、rollback/resume。共享blob Buffer还需确保不可被调用方改写。',verification_design='在隔离副本执行 pnpm --dir .template-source/cli-core test；新增每个持久化阶段的进程中断/异常/rename/fsync失败注入、恢复后目录/mode/hash全等及并发用户修改保留；同一快照init计时、fsync调用数与RSS，cold/hot磁盘分开。物理断电语义需实现设计单独核证，进程kill不能完全代表断电。')
extra_ref(p8,'.template-source/cli-core/transaction.mjs',21)
extra_ref(p8,'.template-source/cli-core/transaction.mjs',164)
extra_ref(p8,'.template-source/cli-core/transaction.mjs',198)
for id in ['P02','P09']:
    c=next(c for c in rows if c['id']==id)
    extra_ref(c,'scripts/sync-strategic-handoff-tools',8)
    c['authority']+=' 已核对 sync-strategic-handoff-tools:8-18 显式声明本体拥有 Context/战略交接/后端交付共享工具，并同步至4个harness；后端有受控import路径替换。'
    c['propagation']='本体 → scripts/sync-strategic-handoff-tools（后端wire路径适配）→4个harness → 对应CLI快照/生成实例。'
p5=next(c for c in rows if c['id']=='P05')
extra_ref(p5,'.template-source/scripts/verify-strategic-handoff-distribution.mjs',27)
p5['semantic_constraints']+=' 另一 strategic-handoff-distribution 三旧CLI初始化已Promise.allSettled并行，不能统一描述全部分发测试串行。'
payload={'schema_version':1,'repository_mode':'template-source','analysis_type':'static-source-risk','measured_here':False,'candidates':rows,'scope_reference':'../scope.md','measurement_reference':'../measurements/runs.jsonl','limitations':['候选并非当前耗时排名；最终顺序需要主控隔离实测。','同名跨仓实现不能默认同源；传播前必须读来源锁和diff。','未运行源码、完整验证、网络、脚手架或同步；仅写分析证据。']}
(OUT/'candidates.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n')
lines=['# 脚本性能静态候选分析','', '范围：本体、9 个 Git 子仓及 scripts 的目录外调用闭包。以下为静态依据，不将历史样本或代码复杂度当作当前耗时。优先次序先服务日常 Plan → Spec → Ticket，再 fast，最后全量/生成/外部依赖；具体收益待主控实测。','', '本轮仅分析，未修改任何运行脚本或副本，不作独立审查或整体完成结论。']
for c in rows:
    lines += ['',f"## {c['id']} {c['title']}",'',f"优先场景：{c['priority']}。触发：{c['trigger']}。",'', '源码：'+ '；'.join(f"`{s['path']}:{s['line']}`" for s in c['sources'])+'。','',f"调用链：{c['call_chain']}。",'',f"成本依据：{c['complexity_or_repetition']}",'',f"候选优化：{c['suggestion']}",'',f"语义约束：{c['semantic_constraints']}",'',f"验证设计：{c['verification_design']}",'',f"权威源：{c['authority']}",'',f"传播：{c['propagation']}"]
lines += ['', '## 不建议当前直接优化与未测范围','', '- 第三方 `scripts/vendor/yaml.mjs`、`xml.mjs` 为锁定依赖生成物。应定位其调用频率及输入规模，不能手改压缩/生成代码；依赖构建入口为 `.template-source/tooling/node/scripts/build-vendor.mjs:75`，版本/闭包来自相邻 package/lock。没有证据支持更换解析器。','- 薄 CLI wrapper/兼容入口本身通常只支付一次启动，优化应落在调用者批量化或共享库；不能删除 CLI 兼容接口。','- fixture 静态 YAML/JSON/模板、许可证、文档不是独立可执行性能对象；测试中的 subprocess/copy 属于测试准备成本，应由场景采样归因。','- 纯解析、术语 hash、确定性 schema/模板生成未见足以支撑专门重写的证据；先按输入规模采样。','- `scripts/lib/maintenance-candidate.mjs:54-83` 候选打包将diff与未跟踪文件聚合内存，`:134`读取全包；大候选可测RSS，但它属于维护冻结，不是普通产品流转。当前不挤占前12优先项。','- `scripts/lib/template-commit-cache.mjs:24-30` 已有有效缓存hit路径，不能笼统宣称“没有缓存”；冷fetch和热校验应分别测。','- 根 scaffold scenario 使用 mock mvnw、前端测试使用 mock pnpm；DDD真实Maven测试需环境才运行，layered离线probe默认跳过。它们不可外推真实构建耗时。','- 真实远端模板获取、npm self-update、真实后端服务、Maven私服和前端安装/构建缺可批准fixture/外部环境的结果记 unknown；不为填满表格调用外部副作用。','', '## 证据核验与不适用理由','', '`candidates.json` 为每个引用保存当前源码 SHA256 和一基行号。运行 `python3 .template-source/evidence/maintenance/2026-09-10-script-performance-audit/hotspots/verify_report.py` 验证引用存在、行号合法和内容摘要一致。','', '业务 behavior-tdd、产品 Spec/Ticket、context reconciliation、Slice 实现批准为 not-applicable：本轮在 template-source 中做只读性能分析，没有改变业务行为或产品资产。候选提出的测试是后续优化验证设计，不是新增门禁，也未声称已执行。']
(OUT/'findings.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'candidate_count':len(rows),'source_refs':sum(len(c['sources']) for c in rows)},ensure_ascii=False))
with (OUT/'findings.md').open('a') as f:
    f.write('''
## 全量实现分类覆盖

`implementation-assessments.csv` 对 inventory 中每个 active unique code SHA 建一行。当前覆盖 320 个 scripts 实现组与 18 个新增目录外实现组，共 338 组；SHA 相同仅证明字节一致，不声明权威归属。每行关联候选或分类为 wrapper、fixture/test、third-party bundle、外部依赖、未确认热点，并给出后续测量方法。精确计数及分类分布见 `coverage-summary.json`。

12 项候选直接引用源码已人工核对；其余采用清单＋源码词法分类，并抽查含进程/树IO的高风险项。这是全量覆盖台账，不等于每个函数都经过实测或被证明无需优化。inventory 的未解析动态边继续保留 unknown；旧 CLI `src/self-update.js` 是显式扩展阅读，不冒充已由 scripts 解析到的闭包。配置 JSON/YAML 用于调用/权威证据，不额外算可执行实现。

第三方或附带工具单列：archify example renderer 通过独立 Node 入口生成5个样例，安全交付器调用 archify；需要具体IR/产物fixture。archify check-update 已有缓存与timeout分支，不建议泛称“无缓存”。LLM Wiki 为本地文档索引/hash，应按页面规模采样；MVC旧 verify_project 实际检查文件/Git状态，不应因 spawn 标记误判为真实 Maven 构建。

## 本轮主控测量的对应关系

已读取 `../measurements/runs.jsonl`、`trace-summary.json` 与 `logs/isolated-plan-entry-0.stdout`：有效合成 Plan entry 首组5次为约180–191毫秒；完整driver进程约989–996毫秒/5次。trace记录每5次有10个Python schema子进程，总计约673毫秒；其中5次Node reconciliation包含自身Python耗时，不能将嵌套计时重复相加。P01的重复启动因此已有本轮样本支持。它仍不能解释整个真实对话超过十分钟。

同一主控隔离样本：strategic-handoff场景20826.652毫秒、frontend-delivery源场景32023.312毫秒，退出码均0；trace版本因插桩会更慢，不能用插桩总时间估计未经插桩收益。CLI初始化fsync成本仍以主控最终trace为准；P08已根据持久化代码调整为协议级候选，blob去重仅作次级优化，不再认定其为分钟级主因。失败Context输入的耗时必须与有效路径分开，不能当正常基准。
''')
